### ISSUE TITLE
向き先をreview-serverに変更

### ISSUE THREAD

**Issue by Akira-Isegawa** [Akira-Isegawa/review-action#5]
# ToDo
- [x] action.ymlの定義を変更
- [x] ci.ymlの定義を変更
- [x] open_api.yamlを参照し、型を生成
- [x] review-serverのクライアントを作成
- [ ] review client 結合テスト
- [ ] review client 単体テスト
- [x] output formatterを移植
- [ ] output formatterのテスト
- [ ] review-filter（github_diffのオブジェクトの値をチェック、制限内ならreview_requestの型に変換）
- [ ] azure_open_ai_client.tsを廃止
- [x] typescriptでテストがしやすいように、ts-jestを入れてみる。
- [ ] リファクタリング
